const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
const DELETE_PRODUCT_FROM_LIST = "DELETE_PRODUCT_FROM_LIST";
const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";

export {
  FETCH_PRODUCTS_SUCCESS,
  FETCH_PRODUCTS_FAILURE,
  DELETE_PRODUCT_FROM_LIST,
  SEARCH_PRODUCTS,
};
